#!/usr/bin/env bash
# Manual deploy to Cloud Run (bypasses GitHub Actions)
# Usage: ./scripts/deploy.sh
set -euo pipefail

PROJECT="tke-phi-privacy-engine"
REGION="us-central1"
SERVICE="llm-council"
REGISTRY="us-central1-docker.pkg.dev/${PROJECT}/llm-council/llm-council"
TAG=$(git rev-parse --short HEAD)
DEPLOY_REVISION=$(git rev-parse HEAD)

echo "Deploying llm-council @ ${TAG} to Cloud Run..."

# Build remotely on Cloud Build (builds amd64 image)
gcloud builds submit \
  --project="${PROJECT}" \
  --region="${REGION}" \
  --tag="${REGISTRY}:${TAG}" \
  --quiet

DIGEST=$(gcloud artifacts docker images describe "${REGISTRY}:${TAG}" \
  --project="${PROJECT}" --format='value(image_summary.digest)')
IMAGE_DIGEST="${REGISTRY}@${DIGEST}"
ROLLOUT_OBSERVATION_SECONDS="${ROLLOUT_OBSERVATION_SECONDS:-30}"
ROLLOUT_HEALTH_SAMPLES="${ROLLOUT_HEALTH_SAMPLES:-1}"
ROLLOUT_SERVICE_HEALTH_SAMPLES="${ROLLOUT_SERVICE_HEALTH_SAMPLES:-50}"
ROLLOUT_SMOKE_SAMPLES="${ROLLOUT_SMOKE_SAMPLES:-5}"
COUNCIL_MAX_LATENCY_SECONDS="${COUNCIL_MAX_LATENCY_SECONDS:-480}"
COUNCIL_MAX_TOKENS="${COUNCIL_MAX_TOKENS:-60000}"
COUNCIL_MAX_COST_USD="${COUNCIL_MAX_COST_USD:-1.50}"
COUNCIL_MAX_ERROR_RATE="${COUNCIL_MAX_ERROR_RATE:-0}"
COUNCIL_MAX_QUALITY_DROP="${COUNCIL_MAX_QUALITY_DROP:-3}"
COUNCIL_MAX_LATENCY_RATIO="${COUNCIL_MAX_LATENCY_RATIO:-1.20}"
COUNCIL_MAX_COST_RATIO="${COUNCIL_MAX_COST_RATIO:-1.25}"
COUNCIL_MIN_ROUTE_SUCCESS="${COUNCIL_MIN_ROUTE_SUCCESS:-0.99}"
export PROJECT REGION SERVICE IMAGE_DIGEST DEPLOY_REVISION ROLLOUT_OBSERVATION_SECONDS
export ROLLOUT_HEALTH_SAMPLES ROLLOUT_SERVICE_HEALTH_SAMPLES ROLLOUT_SMOKE_SAMPLES COUNCIL_MAX_LATENCY_SECONDS
export COUNCIL_MAX_TOKENS COUNCIL_MAX_COST_USD COUNCIL_MAX_ERROR_RATE COUNCIL_MAX_QUALITY_DROP
export COUNCIL_MAX_LATENCY_RATIO COUNCIL_MAX_COST_RATIO COUNCIL_MIN_ROUTE_SUCCESS
scripts/cloud_run_semantic_rollout.sh
echo "Deployed immutable image digest"
