/**
 * AI Agent Types and Interfaces
 * Core types for the CKD note template AI agent system
 */

import type { EncounterData, Alert as SchemaAlert, Section } from "../types/schema"

// Re-export Alert from schema for convenience
export type { Alert } from "../types/schema"

/**
 * Patient context derived from encounter data
 * Used by all agents for clinical decision-making
 */
export interface PatientContext {
  /** CKD Stage: G1, G2, G3a, G3b, G4, G5, G5D */
  ckdStage: string
  /** Albuminuria Stage: A1 (<30), A2 (30-300), A3 (>300) */
  albuminuriaStage: string
  /** GDMT compliance as fraction (0-4 pillars on therapy) */
  gdmtCompliance: number
  /** List of active comorbidities */
  comorbidities: string[]
  /** Patient age in years */
  age?: number
  /** Is patient diabetic */
  isDiabetic?: boolean
  /** Current eGFR value */
  currentEgfr?: number
  /** Current UACR value */
  currentUacr?: number
  /** KFRE 2-year risk percentage */
  kfre2yr?: number
}

/**
 * Input provided to each agent
 */
export interface AgentInput {
  /** Section ID being processed */
  sectionId: string
  /** Current encounter data (key format: "section_id.field_id") */
  currentData: EncounterData
  /** Previous encounter data for comparison */
  previousData: EncounterData
  /** Derived patient context */
  patientContext: PatientContext
  /** Section metadata from registry */
  sectionMeta?: Section
}

/**
 * Action item generated by an agent
 */
export interface ActionItem {
  /** Action description */
  action: string
  /** Priority: urgent, routine, optional */
  priority: "urgent" | "routine" | "optional"
  /** Assigned role: provider, nurse, coordinator, patient */
  assignee?: "provider" | "nurse" | "coordinator" | "patient"
  /** Related medication or order */
  relatedMedication?: string
}

/**
 * Citation for data source
 */
export interface Citation {
  /** Field ID referenced */
  fieldId: string
  /** Value used */
  value: string | number | boolean
  /** Source of the value */
  source: string
  /** Date of the value */
  date?: string
}

/**
 * Output from each agent
 */
export interface AgentOutput {
  /** Clinical interpretation (2-4 sentences) */
  interpretation: string
  /** List of action items */
  actionItems: ActionItem[]
  /** Confidence score (0-1) */
  confidence: number
  /** Flag for provider review */
  reviewNeeded: boolean
  /** Critical findings/alerts */
  alerts: SchemaAlert[]
  /** Patient education summary (plain language) */
  patientEducation?: string
  /** Data citations */
  citations?: Citation[]
}

/**
 * Agent function signature
 */
export type AgentFunction = (input: AgentInput) => Promise<AgentOutput>

/**
 * Agent metadata for registration
 */
export interface AgentMeta {
  /** Unique agent ID */
  agentId: string
  /** Display name */
  displayName: string
  /** Sections owned by this agent */
  sectionsOwned: string[]
  /** Clinical guidelines referenced */
  guidelines: string[]
  /** Confidence threshold for auto-accept */
  confidenceThreshold: number
}

/**
 * Confidence thresholds from agent-config.json
 */
export const CONFIDENCE_THRESHOLDS = {
  AUTO_ACCEPT: 0.9,
  REVIEW_SUGGESTED: 0.7,
  REVIEW_REQUIRED: 0.5,
  REJECT: 0.3,
} as const

/**
 * Alert severity levels
 */
export type AlertSeverity = "critical" | "high" | "medium" | "low"

/**
 * Helper to create an alert
 */
export function createAlert(
  sectionId: string,
  fieldId: string,
  message: string,
  severity: AlertSeverity
): SchemaAlert {
  return {
    id: `${sectionId}.${fieldId}.${Date.now()}`,
    section_id: sectionId,
    field_id: fieldId,
    message,
    severity,
  }
}

/**
 * Helper to create an action item
 */
export function createActionItem(
  action: string,
  priority: ActionItem["priority"] = "routine",
  assignee?: ActionItem["assignee"],
  relatedMedication?: string
): ActionItem {
  return { action, priority, assignee, relatedMedication }
}

/**
 * Default empty agent output
 */
export function emptyAgentOutput(): AgentOutput {
  return {
    interpretation: "",
    actionItems: [],
    confidence: 1.0,
    reviewNeeded: false,
    alerts: [],
  }
}

/**
 * Get field value from encounter data with type safety
 */
export function getField<T>(
  data: EncounterData,
  sectionId: string,
  fieldId: string
): T | undefined {
  const key = `${sectionId}.${fieldId}`
  return data[key] as T | undefined
}

/**
 * Calculate percentage change between two values
 */
export function percentChange(current: number, previous: number): number {
  if (previous === 0) return current > 0 ? 100 : 0
  return ((current - previous) / previous) * 100
}

/**
 * Determine albuminuria stage from UACR
 */
export function getAlbuminuriaStage(uacr: number | undefined): string {
  if (uacr === undefined) return "Unknown"
  if (uacr < 30) return "A1"
  if (uacr <= 300) return "A2"
  return "A3"
}

/**
 * Determine CKD stage from eGFR
 */
export function getCkdStageFromEgfr(egfr: number | undefined): string {
  if (egfr === undefined) return "Unknown"
  if (egfr >= 90) return "G1"
  if (egfr >= 60) return "G2"
  if (egfr >= 45) return "G3a"
  if (egfr >= 30) return "G3b"
  if (egfr >= 15) return "G4"
  return "G5"
}
